### ISSUE TITLE
Uthbert Sword

### ISSUE THREAD

**Issue by Kinjo878** [Shieldwall-TOB/Shieldwall-Script-Library#1]
I want this ancillary vik_sword added when I build vik_master_forge_3

**Comment by DrunkFlamingo** [comment]
@Kinjo878 

The ancillary system appears deprecated in Thrones, how do you want me to proceed with this?

Options:
1. Trait for the owner of the estate?
2. Trait for the faction leader?
3. Scrap it.

**Comment by Kinjo878** [comment]
Make it a trait for the estate owner or the faction leader when they build the final tier of that building line.

**Comment by DrunkFlamingo** [comment]
Will be done when traits are addressed further.
