### ISSUE TITLE
Achers stop shooting with Skirmish Mode enabled in siege battles.

### ISSUE THREAD

**Issue by DrunkFlamingo** [Shieldwall-TOB/Shieldwall-Script-Library#105]
Unknown cause. Not likely to be our fault. Someone should load up vanilla and experiment there. 

1. Load shieldwall. Confirm issue does in fact exist.
2. Load vanilla. check if it occurs there.
3. Report back. If it isn't in vanilla then we broke something.

**Comment by AmericanCaesar** [comment]
Ran several tests, both modded and vanilla and failed to reproduce the error. I'm going to close this. Feel free to reopen if you think it needs further investigation.
