### ISSUE TITLE
The book of vanilla traits that need editing 

### ISSUE THREAD

**Issue by DrunkFlamingo** [Shieldwall-TOB/Shieldwall-Script-Library#114]

**Comment by DrunkFlamingo** [comment]
![20190522185336_1](https://user-images.githubusercontent.com/38512127/58214277-2273eb80-7cc3-11e9-88c6-5ef0dd75897a.jpg)

**Comment by AmericanCaesar** [comment]
Seems simple enough. But why do we need to move it to a new category?
