### ISSUE TITLE
Sometimes the monk population bonus does not accurately reflect what is being displayed.

### ISSUE THREAD

**Issue by AmericanCaesar** [Shieldwall-TOB/Shieldwall-Script-Library#121]
https://i.imgur.com/Sw1x8fL.png

**Comment by DrunkFlamingo** [comment]
Likely a UI error.

**Comment by DrunkFlamingo** [comment]
Yeah that is a known bug with monk pop showing on the ship while foreign pop shows on the monk. System isn't being kept so won't do.
