### ISSUE TITLE
Strange overflow issue with Gwined at starting public order

### ISSUE THREAD

**Issue by AmericanCaesar** [Shieldwall-TOB/Shieldwall-Script-Library#122]
https://i.imgur.com/T2rgqfe.png

**Comment by DrunkFlamingo** [comment]
Bad effect somewhere probably. See what stuff is affecting them and if it happens for anyone else.

**Comment by AmericanCaesar** [comment]
I don't think it is a bad effect because when I open up province details the number breakdown is accurate. It's only in the tooltip that we see the issue. It just Gwined, most other factions also have an issue. The english kingdoms, Strat Clut, and East Engle are the ones who don't have at least one province with a messed up tooltip

**Comment by AmericanCaesar** [comment]
![712100_20190527014738_1](https://user-images.githubusercontent.com/45866301/58408311-6d269800-8022-11e9-9fb1-a20941c5fb6d.png)
![712100_20190527015111_1](https://user-images.githubusercontent.com/45866301/58408312-6d269800-8022-11e9-95b7-5764a9638f26.png)
![712100_20190527014508_1](https://user-images.githubusercontent.com/45866301/58408313-6dbf2e80-8022-11e9-9330-9b93a22d9cad.png)
![712100_20190527014629_1](https://user-images.githubusercontent.com/45866301/58408314-6dbf2e80-8022-11e9-87e8-02b25e3cf0ba.png)
![712100_20190527014641_1](https://user-images.githubusercontent.com/45866301/58408315-6dbf2e80-8022-11e9-9ea3-ee8420d11d32.png)

**Comment by AmericanCaesar** [comment]
My guess is that we messed up the math somewhere in the tooltip code and we're looking at an overflow int error.
