### ISSUE TITLE
Incorrect event triggered for Oppressor trait, trait card is also not loc'd correctly

### ISSUE THREAD

**Issue by AmericanCaesar** [Shieldwall-TOB/Shieldwall-Script-Library#125]
![712100_20190527000017_1](https://user-images.githubusercontent.com/45866301/58402251-b5d75480-8014-11e9-8324-e44cd42c0e42.png)
![712100_20190526233320_1](https://user-images.githubusercontent.com/45866301/58402268-c091e980-8014-11e9-8901-29ec09e310e1.png)

**Comment by DrunkFlamingo** [comment]
More detail please. What exactly is wrong with the event?

**Comment by AmericanCaesar** [comment]
re: "More detail please. What exactly is wrong with the event?"

That's what the first picture is for, but I'll be more specific: it is the wrong card that gets triggered. I think this one is used in peer-to-peer type events? In any case, all the other trait dilemmas use the normal card.

**Comment by AmericanCaesar** [comment]
Here is the educated trait event for comparison:
![image](https://user-images.githubusercontent.com/45866301/58519999-ac600080-816a-11e9-9ee1-2502f2978054.png)

**Comment by DrunkFlamingo** [comment]
This happens for all events when they are targetting the King. Its a bug, but not one I can fix.

**Comment by AmericanCaesar** [comment]
In any case, I mostly created this bug for myself so I can go check it off later after I resolved some of the trait issues. I couldn't figure out how to assign it to myself though :P
