### ISSUE TITLE
Region dilemmas for giving back regions is non-functional

### ISSUE THREAD

**Issue by AmericanCaesar** [Shieldwall-TOB/Shieldwall-Script-Library#126]

**Comment by DrunkFlamingo** [comment]
None functional how? You haven't seen it in a while? It appeared but didn't transfer regions? Need more than this to fix it.

**Comment by AmericanCaesar** [comment]
I have never seen anything at all related to it, even when I think it should have appeared. Early in the Wessex campaign the Nordmann vikings captured one of my regions and Sussex, still my vassal, took it back from them. Nothing ever came back to me. I have also taken regions previous owned by my allies in the Gwined campaign from Mercia and I didn't get any promptings. But overall, I just haven't seen anything pop up for it at all, which makes me think it is currently broken.
