### ISSUE TITLE
Rework the blackmail event (as well others that we want to put in this list)

### ISSUE THREAD

**Issue by AmericanCaesar** [Shieldwall-TOB/Shieldwall-Script-Library#149]
There's a number of default vanilla events that we need to rework to better take advantage of our trait system.

**Comment by AmericanCaesar** [comment]
![20190608204021_1](https://user-images.githubusercontent.com/45866301/60279413-d87bb800-98b5-11e9-96a4-13a1dd69e69f.jpg)

**Comment by AmericanCaesar** [comment]
problems with "vik_politics_assassinate_plot_discovered". Can't get the damn trait to appear

**Comment by DrunkFlamingo** [comment]
Was not fixed.

**Comment by DrunkFlamingo** [comment]
Disabled this event for now.
