### ISSUE TITLE
Crash when the mouse hovers over the second building slot in Nottingham

### ISSUE THREAD

**Issue by AmericanCaesar** [Shieldwall-TOB/Shieldwall-Script-Library#164]
There's not a lot of extra details to discuss beyond what's in the title. I started a new game, went right for Snottingaham, captured it, and the game crashes every time I hover over the second building slot. 

I looked and couldn't find anything in the buildings pack that specifically applies to Nottingham so I think it probably has something to do with startpos.

**Comment by DrunkFlamingo** [comment]
Cause was unused building assigned in start pos. Fixed.
