### ISSUE TITLE
Inflated character stats, probably due to vanilla traits being invisible, but the effect is still there

### ISSUE THREAD

**Issue by AmericanCaesar** [Shieldwall-TOB/Shieldwall-Script-Library#165]
![image](https://user-images.githubusercontent.com/45866301/62184417-d8d2fd00-b312-11e9-9518-f63c77fa8871.png)

There are lots of problems with characters as is pictured here. The starting attributes do not match up with the skills and traits they have, resulting in overinflated stats for many characters. Recently I did see another issue where vanilla traits were showing back up, but now I don't see them anymore with the most recent nightly builds? It seems as if some vanilla traits are still applying an effect.

**Comment by DrunkFlamingo** [comment]
fixed on nightly english pack.
