### ISSUE TITLE
Burghal Faction Effect Strat Clut

### ISSUE THREAD

**Issue by Kinjo878** [Shieldwall-TOB/Shieldwall-Script-Library#171]
https://cdn.discordapp.com/attachments/507357329948409857/608134333642965017/2019-08-06_05_58_20.png

For some reason the Burghal faction effect is showing under Strat Clut, might need to look over the bundle effects.
![2019-08-06_05_58_20](https://user-images.githubusercontent.com/42779070/62509003-6bb1e280-b7be-11e9-88e7-c72ad250d687.png)

**Comment by DrunkFlamingo** [comment]
Fixed on english pack nightly.
